# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Run Unit Test

on:
  push:
    branches: [beta]

jobs:
  test:
    runs-on: macOS-latest # runs a test on Ubuntu, Windows and macOS

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm install

      - name: Run Tests
        run: npm test
